# Generated by Django 5.2.12 on 2026-03-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dx', models.FloatField()),
                ('dy', models.FloatField()),
                ('scene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsc.scene')),
            ],
        ),
    ]
